TicketSystem/Controllers/AdminManageController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketSystem.DataAccess;
using TicketSystem.Model;
using TicketSystem.Models;

namespace TicketSystem.Controllers
{

    public class AdminManageController : Controller
    {
        #region Ctor
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public AdminManageController()
        {
        }

        public AdminManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

        #region UserArea
        [Authorize(Roles = "Admin")]
        public ActionResult ManageUser()
        {
            List<ManageUserViewModel> users = new List<ManageUserViewModel>();
            using (TicketDbContext context = TicketDbContext.Create())
            {
                var roleAdminId = context.Roles.First(r => r.Name == "Admin").Id;
                users = context.Users.Select(x => new
                {
                    Id = x.Id,
                    Email = x.Email,
                    TypeOfTicket = x.TypeOfTicket,
                    Roles = (from userRole in x.Roles
                             join role
                             in context.Roles on userRole.RoleId
                             equals role.Id
                             select role.Name).ToList()
                }).ToList().Select(p => new ManageUserViewModel()
                {
                    Id = p.Id,
                    Email = p.Email,
                    TypeOfTicket = p.TypeOfTicket,
                    Role = string.Join(",", p.Roles)
                }).ToList();
            }
            users = users.Where(x => x.Role != "Admin").ToList();
            foreach (var user in users)
            {
                if (user.Role == "User")
                    user.TypeOfTicket = null;
            }
            return View(users);
        }

        // GET: AdminManage/EditUser/
        [Authorize(Roles = "Admin")]
        public ActionResult EditUser(string id)
        {
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Helper", Value = "0" });

            items.Add(new SelectListItem { Text = "User", Value = "1", Selected = true });

            items.Add(new SelectListItem { Text = "Admin", Value = "2" });

            ViewBag.Roles = items;

            var user = UserManager.FindById(id);

            EditUserViewModel editUser = new EditUserViewModel();

            using (var context = TicketDbContext.Create())
            {
                editUser = new EditUserViewModel()
                {
                    Email = user.Email,
                };
            }
            return View(editUser);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult EditUserAdvande(string id)
        {
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Helper", Value = "0", Selected = true });

            items.Add(new SelectListItem { Text = "User", Value = "1" });

            items.Add(new SelectListItem { Text = "Admin", Value = "2" });

            ViewBag.Roles = items;

            var user = UserManager.FindById(id);

            EditUserViewModel editUser = new EditUserViewModel();

            using (var context = TicketDbContext.Create())
            {
                editUser = new EditUserViewModel()
                {
                    Email = user.Email,
                    TypeOfTicket = user.TypeOfTicket
                };
            }
            return View(editUser);
        }

        // POST: AdminManage/EditUser/
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult EditUser(string id, EditUserViewModel collection, string Roles)
        {
            try
            {
                using (TicketDbContext context = TicketDbContext.Create())
                {
                    var user = UserManager.FindById(id);

                    if (Roles == "0")
                    {
                        var collec = UserManager.GetRoles(user.Id);
                        RemoveRolesFromUser(user, collec);
                        UserManager.AddToRole(user.Id, "Helper");
                    }
                    else if (Roles == "1")
                    {
                        var collec = UserManager.GetRoles(user.Id);
                        RemoveRolesFromUser(user, collec);
                        UserManager.AddToRole(user.Id, "User");
                    }
                    else
                    {
                        var collec = UserManager.GetRoles(user.Id);
                        RemoveRolesFromUser(user, collec);
                        UserManager.AddToRole(user.Id, "Admin");
                    }
                    context.SaveChanges();
                }
                return RedirectToAction("ManageUser");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult EditUserAdvande(string id, EditUserViewModel collection, string Roles)
        {
            try
            {
                using (TicketDbContext context = TicketDbContext.Create())
                {
                    var user = context.Users.FirstOrDefault(x => x.Id == id);

                    if (Roles == "0")
                    {
                        var collec = UserManager.GetRoles(user.Id);
                        RemoveRolesFromUser(user, collec);
                        UserManager.AddToRole(user.Id, "Helper");
                    }
                    else if (Roles == "1")
                    {
                        var collec = UserManager.GetRoles(user.Id);
                        RemoveRolesFromUser(user, collec);
                        UserManager.AddToRole(user.Id, "User");
                    }
                    else
                    {
                        var collec = UserManager.GetRoles(user.Id);
                        RemoveRolesFromUser(user, collec);
                        UserManager.AddToRole(user.Id, "Admin");
                    }
                    user.TypeOfTicket = collection.TypeOfTicket;

                    context.SaveChanges();
                }
                return RedirectToAction("ManageUser");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminManage/Delete/
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteUser(string id)
        {
            var user = UserManager.FindById(id);
            if (null == user)
            {
                return new HttpNotFoundResult("Specjalnie tu trafiłeś?");
            }
            var model = new ManageUserViewModel() { Email = user.Email, TypeOfTicket = user.TypeOfTicket, Id = user.Id };
            return View(model);
        }

        // POST: AdminManage/Delete/
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult DeleteUser(string id, FormCollection collection)
        {
            try
            {
                UserManager.Delete(UserManager.FindById(id));

                return RedirectToAction("ManageUser");
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region TicketArea
        [Authorize(Roles = "Helper, Admin")]
        public ActionResult ManageTicket()
        {
            List<ManageTicketViewModel> tickets = new List<ManageTicketViewModel>();
            using (TicketDbContext context = TicketDbContext.Create())
            {
                tickets = context.Tickets.Select(x
                   => new ManageTicketViewModel()
                   {
                       Title = x.Title,
                       TypeOfTicket = x.TypeOfTicket,
                       UserName = x.User.UserName,
                       Id = x.TicketId
                   }).ToList();
            }
            return View(tickets);
        }

        [Authorize(Roles = "Helper, Admin")]
        public ActionResult DetailsTicket(int id)
        {
            List<Ticket> ticket = new List<Ticket>();
            using (var context = TicketDbContext.Create())
            {
                ticket = context.Tickets.Where(x => x.TicketId == id).ToList();
            }
            if (null == ticket)
                return new HttpNotFoundResult("Specjalnie tu trafiłeś?");

            return View(ticket);
        }

        [Authorize(Roles = "Helper, Admin")]
        public ActionResult EditTicket(int id)
        {
            EditTicketViewModel ticketToEdit = new EditTicketViewModel();
            using (var context = TicketDbContext.Create())
            {
                ticketToEdit = context.Tickets.Where(x => x.TicketId == id)
                    .Select(x => new EditTicketViewModel()
                    {
                        Id = x.TicketId,
                        StatusOfTicket = x.StatusOfTicket,

TicketSystem/Controllers/TicketController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Linq;
using System.Web.Mvc;
using TicketSystem.DataAccess;
using TicketSystem.Model;
using TicketSystem.Models;

namespace TicketSystem.Controllers
{
    public class TicketController : Controller
    {

        private TicketDbContext _context;

        public TicketController()
        {
            _context = TicketDbContext.Create();
        }


        // GET: Zwaraca formularz do wypełnienia zgłoszenia
        [Authorize]
        [HttpGet]
        public ActionResult Add()
        {
            var ticketVM = new TicketViewModel
            {
                IsSuccess = false,
                //Message = "Wypełnij poniższy formularz aby dodać zgłoszenie."
            };
            return View(ticketVM);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize]
        public ActionResult Add(TicketViewModel ticketForm)
        {
            if (!ModelState.IsValid)
                return View(ticketForm);

            var userId = User.Identity.GetUserId();
            var ticketToDb = new Ticket
            {
                UserId = userId,
                Title = ticketForm.Title,
                Description = ticketForm.Description,
                TypeOfTicket = ticketForm.TypeOfTicket,
                StatusOfTicket = StatusesOfTicket.Zalozony,
                CreationTime = DateTime.Now,

            };

            _context.Tickets.Add(ticketToDb);
            _context.SaveChanges();

            ModelState.Clear();
            return View(new TicketViewModel(true));
        }

        [Authorize]
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var userTickets = _context
                .Tickets
                .Where(u => u.UserId == userId)
                .OrderByDescending(x => x.CreationTime)
                .ToList();



            return View(userTickets);
        }
    }
}

TicketSystem/Views/Shared/ManageTicket.cshtml
@model IEnumerable<TicketSystem.Models.ManageTicketViewModel>
@{
    ViewBag.Title = "ManageTicket";
}
<h2>Zarządzaj zgłoszeniami</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfTicket)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfTicket)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "EditTicket", new { id = item.Id }) |
                @Html.ActionLink("Szczegóły", "DetailsTicket", new { id = item.Id }) |
                @Html.ActionLink("Usuń", "DeleteTicket", new { id = item.Id })
            </td>
        </tr>
    }
</table>

TicketSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ticket System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Wyślij zgłoszenie", "Add", "Ticket")</li>
                    <li>@Html.ActionLink("Moje zgłoszenia", "Details", "Ticket")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Zarządzaj
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Zarządzaj użytkownikami", "ManageUser", "AdminManage")</li>
                                <li>@Html.ActionLink("Zarządzaj ticketami", "ManageTicket", "AdminManage")</li>
                            </ul>
                        </li>
                    }
                    else if(User.IsInRole("Helper"))
                    {
                        <li>@Html.ActionLink("Zarządzaj ticketami", "ManageTicket", "AdminManage")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year — Ticket System - Aplikacja na zaliczenie ISK</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval") <!-- *required for client side validation! -->
    @RenderSection("scripts", required: false)
</body>
</html>

TicketSystem/Views/Shared/_TicketDetailPartial.cshtml
@using TicketSystem.Model
@{
    ViewBag.Title = "Moje zgłoszenia";
    int idx = 1;//zmiena do numerowania wierszy w tabeli
}
@if (Model.Count == 0)
{
    <div class="alert alert-warning" role="alert">
        Nie posiadasz żadnych zgłoszeń
    </div>
}
else
{
    <div class="@*table-responsive*@">
        <table @*class="table table-hover"*@ id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tytuł</th>
                    <th scope="col">Opis</th>
                    <th scope="col">Typ</th>
                    <th scope="col">Data utworzenia</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var ticket in Model)
                {


                    <tr>
                        <th scope="row">@idx</th>
                        <td>@ticket.Title</td>
                        <td style="word-wrap: break-word; max-width: 200px;">@ticket.Description</td>
                        <td>@ticket.TypeOfTicket</td>
                        <td>@ticket.CreationTime</td>
                        <td>

                            @switch (ticket.StatusOfTicket)
                            {
                                case StatusesOfTicket.Zalozony:
                                    <button type="button" class="btn btn-danger">@ticket.StatusOfTicket</button>
                                    break;

                                case StatusesOfTicket.W_trakcie:
                                    <button type="button" class="btn btn-warning">@ticket.StatusOfTicket</button>
                                    break;

                                case StatusesOfTicket.Zrobiony:
                                    <button type="button" class="btn btn-success">@ticket.StatusOfTicket</button>
                                    break;
                            }

                        </td>
                    </tr>
                    idx++;
                }

            </tbody>
        </table>
    </div>
}

<link rel="stylesheet" type="text/css" href="/Content/datatables.min.css" />



@section scripts
{
    <script type="text/javascript" src="/Scripts/datatables.min.js"></script>
    <script>

        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>


}